#!/usr/bin/env bash
# This Bash script displays numbers from 1 to 100.
# It follows these rules:
# - Displays FizzBuzz when the number is a multiple of 3 and 5
# - Displays Fizz when the number is a multiple of 3
# - Displays Buzz when the number is a multiple of 5
# - Otherwise, it displays the number
# The output is presented in a list format.

i=1

while [ $i -le 100 ]; do
      if [ $((i%5)) -eq 0 ] && [ $((i%3)) -eq 0 ]; then
	  echo "FizzBuzz"
      elif [ $((i%5)) -eq 0 ]; then
	  echo "Buzz"
      elif [ $((i%3)) -eq 0 ]; then
	  echo "Fizz"
      else
	  echo "$i"
      fi
      i=$((i+1))
done
