#!/usr/bin/env bash
# This Bash script displays Best School 10 times

count=0
while [ $count -lt 10 ];
do
    if [ $count -eq 9 ];
    then
	echo "hi"
    fi
    echo "Best School"
    (( count++ ))
done
