#!/usr/bin/env bash
# This Bash script displays Best School 10 times but Hi on 9th iteration

count=1
while [ $count -lt 21 ];
do
    echo $count
    case $count in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
    esac
    (( count++ ))
done
