#!/usr/bin/env bash
# This Bash script displays Best School 10 times but Hi on 9th iteration

hours=0
while [ $hours -lt 13 ];
do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -lt 60 ];
    do
	echo "$minutes"
	minutes=$((minutes+1))
    done
    (( hours++ ))
done
