#!/usr/bin/env bash
# This script configures an Ubuntu server with the suggested requirements

# Backup the original hosts
cp /etc/hosts /tmp/hosts_bkup

# Update localhost entry to resolve 127.0.0.2
grep -q "localhost" /etc/hosts || echo -e "\n127.0.0.2\tlocalhost" >> /etc/hosts

# Update facebook.com entry to resolve 8.8.8.8
grep -q "facebook.com" /etc/hosts || echo -e "\n8.8.8.8\tfacebook.com" >> /etc/hosts

# Clean backup files
rm /tmp/hosts_backup
